# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yJZZi3fVB8MEfGOu4osJCR_ObJIWIAYo
"""

import os

# Paste your copied keys inside the quotation marks
os.environ["AWS_ACCESS_KEY_ID"] = "PASTE_YOUR_ACCESS_KEY_ID_HERE"
os.environ["AWS_SECRET_ACCESS_KEY"] = "PASTE_YOUR_SECRET_ACCESS_KEY_HERE"
os.environ["AWS_DEFAULT_REGION"] = "us-east-1"  # Change this if your resources are in a different region

import json
import logging
import time
from concurrent.futures import ThreadPoolExecutor

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("AWSSecurityAuditorSIM")

class AWSSecurityAuditorSimulation:
    def __init__(self):
        self.findings = []

    def audit_iam_root_mfa(self):
        logger.info("Auditing IAM credential report for Root MFA... [SIMULATION]")
        time.sleep(0.5)
        # Simulating a finding: Root account lacks MFA
        self.findings.append({
            "Service": "IAM",
            "Severity": "CRITICAL",
            "Resource": "Root Account",
            "Issue": "Root account does not have Multi-Factor Authentication (MFA) enabled."
        })

    def audit_s3_buckets(self):
        logger.info("Auditing S3 Buckets for public access block... [SIMULATION]")
        time.sleep(0.5)
        # Simulating a finding: Exposed bucket
        self.findings.append({
            "Service": "S3",
            "Severity": "HIGH",
            "Resource": "prod-user-data-backup-2026",
            "Issue": "Public Access Block is not fully enabled on this bucket."
        })

    def audit_security_groups(self):
        logger.info("Auditing EC2 Security Groups for overly permissive rules... [SIMULATION]")
        time.sleep(0.5)
        # Simulating a finding: Open SSH port
        self.findings.append({
            "Service": "EC2/VPC",
            "Severity": "HIGH",
            "Resource": "sg-0abc1234567def",
            "Issue": "Security Group allows unrestricted inbound access (0.0.0.0/0) to sensitive port ranges (22-22)."
        })

    def audit_rds_encryption(self):
        logger.info("Auditing RDS Instances for storage encryption... [SIMULATION]")
        time.sleep(0.5)
        # Simulating a healthy check (no findings added)
        logger.info("RDS Check complete. No unencrypted databases found.")

    def run_parallel_audit(self):
        audit_functions = [
            self.audit_iam_root_mfa,
            self.audit_s3_buckets,
            self.audit_security_groups,
            self.audit_rds_encryption
        ]
        with ThreadPoolExecutor(max_workers=4) as executor:
            executor.map(lambda func: func(), audit_functions)
        return self.findings

if __name__ == "__main__":
    auditor = AWSSecurityAuditorSimulation()
    print("\n" + "="*60)
    print(" STARTING ADVANCED AWS SECURITY AUDIT (SIMULATED MODE) ")
    print("="*60 + "\n")

    report = auditor.run_parallel_audit()

    print("\n" + "="*60)
    print(f" AUDIT COMPLETE. FINDINGS DETECTED: {len(report)} ")
    print("="*60 + "\n")
    print(json.dumps(report, indent=4))